import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navb from '../Components/Navb';
import Apre from '../Components/Apre';
import Api from '../Components/Api';
import Formu from '../Components/Form';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CTST-Dourados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="icon.ico" />
      </Head>
      <Navb/>
      <div className={styles.slids}>
        <img src='bannerpc.png' className={styles.slidspc}/>
        <img src='bannercell.png' className={styles.slidscl}/>
      </div>
      <Api/>
      <main className={styles.main}>
        <Apre/>
        <div className={styles.maini}>
          <p>body</p>
        </div>
        <div className={styles.conta}>
          <div>
            
          </div>
          <form name="contact" method="POST" data-netlify="true">
            <p>
              <label>Your Name: <input type="text" name="name" /></label>
            </p>
            <p>
              <label>Your Email: <input type="email" name="email" /></label>
            </p>
            <p>
              <label>Your Role: <select name="role[]" multiple>
                <option value="leader">Leader</option>
                <option value="follower">Follower</option>
              </select></label>
            </p>
            <p>
              <label>Message: <textarea name="message"></textarea></label>
            </p>
            <p>
              <button type="submit">Send</button>
            </p>
          </form>

        </div>
      </main>
    </div>
  )
}